#!/usr/bin/python

"""
.. executable:: acmed
    :synopsis: Execution endpoint used to initiate ACME system and user daemons 
    :platform: OSX, Ubuntu

.. moduleauthor:: Beau Hunter <beauhunt@amazon.com>

"""

import sys, os
import logging

sys.path.insert(0,"/usr/local/amazon/lib")





import acme.daemon

if __name__ == "__main__":
    logger = logging.getLogger("cli")
    try:
        cli = acme.daemon.cli
        cli.arguments = sys.argv[1:]
        sys.exit(cli.run())
    except KeyboardInterrupt as exp:
        ## We try to catch this in run(), but for some reason it occasionally
        ## fails under Ubuntu.
        if cli.acme_server.server_thread.is_alive():
            logger.warning("Recieved Keyboard Interrupt, shutting down...")
            cli.acme_server.stop()
        pass
    except Exception as exp:
        message = "An unknown critical error occurred: {}".format(exp.message)
        logger.critical(message,exc_info=1)
        
        ## Log to stderr in case there's something wrong with our logger
        sys.stderr.write("{}\n".format(message))
        sys.stderr.flush()
        
        sys.exit(99)
